import React from 'react';
import { ChevronDown, Pencil, Check } from 'lucide-react';
import { SectionShell } from './SectionShell';
import { EXPERIENCE } from '../content';
import type { ExperienceEntry } from '../types';

const INPUT='w-full rounded border border-border bg-background px-2 py-1.5 text-sm text-foreground outline-none focus-visible:ring-2 focus-visible:ring-primary';
function useLandscape(){const[q,setQ]=React.useState(()=>typeof window!=='undefined'&&window.matchMedia('(orientation: landscape)').matches);React.useEffect(()=>{const m=matchMedia('(orientation: landscape)'),f=()=>setQ(m.matches);m.addEventListener('change',f);return()=>m.removeEventListener('change',f)},[]);return q}
export function ExperiencePage():React.ReactElement{
 const[entries,setEntries]=React.useState(()=>EXPERIENCE.map(e=>({...e,highlights:[...e.highlights]})));
 const[open,setOpen]=React.useState<Set<number>>(()=>new Set([EXPERIENCE.length-1]));
 const[editing,setEditing]=React.useState<number|null>(null);const[draft,setDraft]=React.useState<ExperienceEntry|null>(null);const landscape=useLandscape();
 const toggle=(i:number)=>setOpen(p=>{const n=new Set(p);n.has(i)?n.delete(i):n.add(i);return n});
 const start=(i:number)=>{setDraft({...entries[i],highlights:[...entries[i].highlights]});setEditing(i);setOpen(p=>new Set(p).add(i))};
 const save=()=>{if(editing===null||!draft)return;setEntries(p=>p.map((e,i)=>i===editing?{...draft,highlights:draft.highlights.map(x=>x.trim()).filter(Boolean)}:e));setEditing(null);setDraft(null)};
 const rows=landscape?entries.map((e,i)=>({e,i})):entries.map((e,i)=>({e,i})).reverse();
 return <SectionShell eyebrow="Experience" placeholderNote={false}><div className={landscape?'-mx-5 overflow-x-auto px-5 pb-2':''}><ol className={landscape?'flex min-w-max':'flex flex-col'}>{rows.map(({e,i})=>{const shown=open.has(i),edit=editing===i&&draft;return <li key={i} className={landscape?'w-[280px] shrink-0 px-2':'border-l-2 border-border pb-5 pl-5'}><button onClick={()=>toggle(i)} aria-expanded={shown} className="w-full rounded p-2 text-left hover:bg-surfaceAlt focus-visible:ring-2 focus-visible:ring-primary"><span className="flex justify-between"><span className="text-[11px] font-semibold uppercase tracking-wide text-primary">{e.period}</span><ChevronDown className={`h-4 w-4 transition-transform ${shown?'rotate-180':''}`}/></span><span className="block font-display text-sm font-semibold">{e.role}</span><span className="block text-xs text-foregroundMuted">{e.company} · {e.location}</span></button><div className="grid transition-[grid-template-rows] duration-300" style={{gridTemplateRows:shown?'1fr':'0fr'}}><div className="overflow-hidden"><div className="mt-2 rounded border border-border bg-surface p-4">{edit?<div className="space-y-2"><input className={INPUT} value={draft.period} onChange={x=>setDraft({...draft,period:x.target.value})}/><input className={INPUT} value={draft.role} onChange={x=>setDraft({...draft,role:x.target.value})}/><input className={INPUT} value={draft.company} onChange={x=>setDraft({...draft,company:x.target.value})}/><input className={INPUT} value={draft.location} onChange={x=>setDraft({...draft,location:x.target.value})}/><textarea className={INPUT} rows={3} value={draft.summary} onChange={x=>setDraft({...draft,summary:x.target.value})}/><textarea className={INPUT} rows={4} value={draft.highlights.join('\n')} onChange={x=>setDraft({...draft,highlights:x.target.value.split('\n')})}/><button onClick={save} className="inline-flex items-center gap-1 rounded bg-primary px-3 py-2 text-sm font-semibold text-accentForeground"><Check className="h-4 w-4"/>Save</button></div>:<><div className="flex items-start gap-2"><p className="flex-1 text-sm leading-relaxed text-foregroundMuted">{e.summary}</p><button onClick={()=>start(i)} aria-label={`Edit ${e.role}`} className="rounded-full p-2 hover:bg-surfaceAlt"><Pencil className="h-4 w-4"/></button></div><ul className="mt-3 space-y-1.5">{e.highlights.map((h,j)=><li key={j} className="flex gap-2 text-sm"><span className="mt-2 h-1 w-1 shrink-0 rounded-full bg-primary"/>{h}</li>)}</ul></>}</div></div></div></li>})}</ol></div></SectionShell>
}
