import type { Certification, ExperienceEntry, ProjectEntry } from './types';
export const ABOUT_INTRO = 'A motivated, industrious manufacturing engineer technician with deep hands-on experience across advanced manufacturing. I have a passion for learning, creativity, research and exploration — and I enjoy contributing to a team’s cohesiveness and overall productivity. Over the years I have grown from the warehouse floor into prototype, process and automation work, always chasing the next problem worth solving. Based in Portland, OR.';
export const ABOUT_FOCUS = ['Creative & Innovative','Quick learner & Autodidactic','Communicates & Collaborates','Technical Troubleshooting','Engaging & Curious','Documentation & Education','Lean & 6σ Certified','Robotics & Automation'];
export const EXPERIENCE: ExperienceEntry[] = [
{role:'Top Gun Inventory Specialist',company:'RGIS',location:'Syracuse, NY',period:'2011 – 2014',summary:'Audited physical inventory accuracy for retail clients and reconciled it against perpetual records — early, data-driven problem solving.',highlights:['Assessed the accuracy of physical inventory counts','Calculated loss by comparing perpetual and physical inventory in software','Reviewed data with clients and troubleshot discrepancies','Operated RF scanners and inventory software']},
{role:'CR Palletizer',company:'McLane Northeast',location:'Syracuse, NY',period:'2013 – 2014',summary:'Fast-paced distribution work staging outgoing shipments and keeping automated conveyor systems running.',highlights:['Organized ~80 lb totes and staged them on pallets for shipment','Safely operated a forklift throughout the warehouse','Sustained high productivity in a safe work environment','Troubleshot automated conveyor systems']},
{role:'Advanced Rack Technician',company:'Advanced Metal Finishing',location:'Rocklin, CA',period:'2015',summary:'Ran precision metal-finishing processes and quality control on critical, specialized parts.',highlights:['Operated anodize and Alodine finishing processes','Performed quality control on critical anodize and Alodine parts','Certified to process specialized parts for chromate conversions','Supported departments across the factory']},
{role:'Lead Product Development Engineer Technician',company:'Nike AirMI',location:'Beaverton, OR',period:'2015 – 2025',summary:'A decade advancing prototype and production processes across thermoforming, injection, extrusion and RF welding — with a growing focus on machine vision, robotics and controls.',highlights:['Daily troubleshooting of pneumatic, hydraulic, electromechanical and thermal systems','Developed prototype guidelines using the Cognex machine-vision system','Programmed Denso and ABB robotics with Wincaps III and RobotStudio','Applied Lean and 6 Sigma tools to improve reliability and functionality','Collaborated with Maintenance, Materials, and Automation & Controls teams','Mentored teammates and drove systematic root-cause troubleshooting']},
{role:'Principal, FW Molded Component Engineer Technician',company:'Nike BFL',location:'Beaverton, OR',period:'2025 – Present',summary:'Prototyping and processing advanced molded components while piloting automation and data collection in the carbon area.',highlights:['Prototypes and processes carbon plates, foams, rubber and plastics','Designs and runs studies to optimize the carbon-area process','Piloting an automated data-collection program for material usage','Doubled output volume per cycle for high-volume orders (proof of concept)','Partners with vendors to install new equipment and troubleshoot existing lines']}
];
export const CERTIFICATIONS: Certification[]=[{name:'Lean Manufacturing',issuer:'Manufacturing certification',year:'—',status:'Certified'},{name:'Six Sigma (6σ)',issuer:'Manufacturing certification',year:'—',status:'Certified'},{name:'Chromate Conversion Processing',issuer:'Advanced Metal Finishing',year:'2015',status:'Certified'}];
export const PROFICIENCIES=[{group:'Robotics & Controls',items:['Denso robotics · Wincaps III','ABB robotics · RobotStudio']},{group:'Machine Vision',items:['Cognex vision systems']},{group:'Manufacturing Processes',items:['Thermoforming','Injection','Extrusion','RF welding']},{group:'Systems & Analysis',items:['SAP','JMP','Smartsheet','Wrike','Excel','Infinity']}];
export const ENGINEERING_PROJECTS: ProjectEntry[]=[
{title:'Process Optimization Studies',category:'Process',summary:'Designed and implemented studies to optimize molding and carbon-area processes, using structured experiments and JMP to improve capability.',tags:['DOE','JMP','Process capability']},
{title:'Prototype & Process Development',category:'Development',summary:'Developed prototypes and processes across thermoforming, injection, extrusion and RF welding — from concept toward production readiness.',tags:['Thermoforming','Injection','Extrusion','RF welding']},
{title:'Technical Troubleshooting',category:'Systems',summary:'Root-cause troubleshooting across pneumatic, hydraulic, electromechanical and thermal systems to keep production reliable.',tags:['Pneumatic / hydraulic','Electromechanical','Root cause']},
{title:'Equipment Procurement & Footprint',category:'Facilities',summary:'Procured equipment to meet storage and capacity needs while improving the overall production footprint.',tags:['Procurement','Capacity','Layout']},
{title:'Vendor Collaboration',category:'Integration',summary:'Partnered with vendors to install new equipment and troubleshoot existing lines through commissioning.',tags:['Vendor','Install','Commissioning']}
];
export const AUTOMATION_PROJECTS: ProjectEntry[]=[
{title:'Industrial Robotics',category:'Robotics',summary:'Programmed and integrated Denso and ABB robots using Wincaps III and RobotStudio for handling and process tasks.',tags:['Denso','ABB','Wincaps III','RobotStudio']},
{title:'Machine-Vision Guidelines',category:'Machine Vision',summary:'Developed prototype guidelines and inspection routines using the Cognex vision system.',tags:['Cognex','Inspection','Guidance']},
{title:'Automated Data Collection',category:'Industry 4.0',summary:'Began implementing an automated data-collection program for material usage to replace manual tracking (pilot).',tags:['Data collection','Material usage','Pilot']},
{title:'High-Volume Output',category:'Automation',summary:'Worked with design to double output volume per cycle for high-volume orders as a proof of concept.',tags:['Throughput','Cycle time','PoC']},
{title:'Conveyors & Controls',category:'Controls',summary:'Troubleshot automated conveyor systems and collaborated with Automation & Controls teams.',tags:['Conveyors','Controls','Integration']}
];
